1e-05
batch_time: 0.38173961639404297
  0%|                                                                                                                                                                                                                                                | 0/9000 [00:00<?, ?it/s]
get_batch_contrastive_loss time: 1.2216339111328125
passed train_by_single_batch
batch_time: 4.163089036941528
get_batch_contrastive_loss time: 0.9547562599182129
passed train_by_single_batch
An arbitrary loader is used instead of Validation loader
Traceback (most recent call last):
  File "emb_train.py", line 183, in <module>
    trainer.train_by_num_epoch(args.num_epochs)
  File "/home/clay/userdata/title_generation/emb_trainer.py", line 155, in train_by_num_epoch
    validation_dict_train = self.validate(external_loader=self.train_loader)
  File "/home/clay/userdata/title_generation/emb_trainer.py", line 519, in validate
    if idx in sorted_cos_idx[idx][-topk:]: # pick best 20 scores
IndexError: index 2654 is out of bounds for axis 0 with size 2654